"""
Summarise output/classifications.jsonl into evidence/classification_run.md.

Reproducible evidence of a classification run: sources (rule / dedup / cache / live), tokens
and cost, latency, distribution by reason and flag, confidence bands with the low-confidence
messages listed, secondary reasons, entity fill rates, post-processing codes, and agreement
with the example ids in policy/taxonomy.yaml (the assistant's reading-based pre-labels, not a
gold set: disagreements are the first candidates for human review in the evaluation step).

    python scripts/summarize_classifications.py [output/classifications.jsonl]
"""
from __future__ import annotations

import json
import statistics
import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_IN = ROOT / "output" / "classifications.jsonl"
OUT = ROOT / "evidence" / "classification_run.md"
TAXONOMY = yaml.safe_load((ROOT / "lumo_triage" / "policy" / "taxonomy.yaml").read_text(encoding="utf-8"))
ROUTING = yaml.safe_load((ROOT / "lumo_triage" / "policy" / "routing.yaml").read_text(encoding="utf-8"))
THRESHOLD = float(ROUTING["confidence_threshold"])


def pct(n: int, d: int) -> str:
    return f"{100 * n / d:.1f} %" if d else "-"


def p(values: list[int], q: float) -> int:
    if not values:
        return 0
    s = sorted(values)
    return s[min(len(s) - 1, int(round(q * (len(s) - 1))))]


def short(text: str, n: int = 90) -> str:
    text = text.replace("|", "/").replace("\n", " ")
    return text if len(text) <= n else text[: n - 1] + "…"


def source_of(r: dict) -> str:
    if r["classification"] is None:
        return "failed"
    if r.get("reused_from"):
        return "dedup"
    if r.get("llm") is None:
        return "rule"
    return "cache" if r["llm"]["from_cache"] else "live"


def main(path: Path) -> None:
    records = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    n = len(records)
    classified = [r for r in records if r["classification"]]
    with_llm = [r for r in records if r.get("llm")]
    sources = Counter(source_of(r) for r in records)

    lines: list[str] = []
    add = lines.append
    add("# Classification run — evidence")
    add("")
    add(f"Generated by `scripts/summarize_classifications.py` from `{path.relative_to(ROOT).as_posix()}` "
        f"({n} records). Prompt version and model are recorded per message in that file.")
    add("")

    # ---------------------------------------------------------------- 1. run summary
    add("## 1. Run summary")
    add("")
    add("| Item | Value |")
    add("|---|---|")
    add(f"| Messages | {n} |")
    add(f"| Decided by rules (tier-0) | {sources.get('rule', 0)} |")
    add(f"| Reused from an exact duplicate | {sources.get('dedup', 0)} |")
    add(f"| Model, live call | {sources.get('live', 0)} |")
    add(f"| Model, replayed from cache | {sources.get('cache', 0)} |")
    add(f"| Unclassified (model failure) | {sources.get('failed', 0)} |")
    served = Counter(r["llm"]["served_by"] for r in with_llm)
    add(f"| Served by | {', '.join(f'{k}: {v}' for k, v in served.most_common())} |")
    inp = sum(r["llm"]["input_tokens"] for r in with_llm)
    read = sum(r["llm"]["cache_read_tokens"] for r in with_llm)
    write = sum(r["llm"]["cache_write_tokens"] for r in with_llm)
    outp = sum(r["llm"]["output_tokens"] for r in with_llm)
    prompt_tokens = inp + read + write
    add(f"| Prompt tokens: uncached / cache read / cache write | {inp:,} / {read:,} / {write:,} |")
    add(f"| Cache-read share of prompt tokens | {pct(read, prompt_tokens)} |")
    add(f"| Output tokens (JSON plus thinking) | {outp:,} (mean {outp / len(with_llm):.0f} per call) |" if with_llm else "| Output tokens | 0 |")
    cost = sum(r["llm"]["cost_usd"] for r in with_llm)
    add(f"| Cost of the model calls (when made) | USD {cost:.4f} (USD {cost / len(with_llm):.4f} per call) |" if with_llm else "| Cost | 0 |")
    lat = [r["llm"]["latency_ms"] for r in with_llm if r["llm"]["latency_ms"]]
    add(f"| Latency per call, p50 / p95 / max | {p(lat, .5):,} / {p(lat, .95):,} / {max(lat):,} ms |" if lat else "| Latency | - |")
    add("")

    # ---------------------------------------------------------------- 2. reasons
    add("## 2. Primary reason distribution")
    add("")
    by_reason: dict[str, list[float]] = defaultdict(list)
    for r in classified:
        by_reason[r["classification"]["primary_reason"]].append(r["classification"]["confidence"])
    add("| Primary reason | n | share | mean conf. | min conf. |")
    add("|---|---:|---:|---:|---:|")
    for reason, confs in sorted(by_reason.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        add(f"| `{reason}` | {len(confs)} | {pct(len(confs), len(classified))} | {statistics.mean(confs):.2f} | {min(confs):.2f} |")
    zero = [r["id"] for r in TAXONOMY["reasons"] if r["id"] not in by_reason]
    add("")
    add(f"Reasons with no message in this run: {', '.join(f'`{z}`' for z in zero) if zero else 'none'}.")
    add("")

    # ---------------------------------------------------------------- 3. flags
    add("## 3. Flags")
    add("")
    flag_counts = Counter()
    fraud_flag_other_reason = 0
    human_flag_other_reason = 0
    for r in classified:
        c = r["classification"]
        for k, v in c["flags"].items():
            if v:
                flag_counts[k] += 1
        if c["flags"]["fraud_or_security"] and c["primary_reason"] != "fraude_seguridad":
            fraud_flag_other_reason += 1
        if c["flags"]["requests_human"] and c["primary_reason"] != "hablar_con_humano":
            human_flag_other_reason += 1
    add("| Flag | n |")
    add("|---|---:|")
    for fid in TAXONOMY["flags"]:
        add(f"| `{fid}` | {flag_counts.get(fid, 0)} |")
    add("")
    add(f"Messages with any flag: {sum(1 for r in classified if any(r['classification']['flags'].values()))}. "
        f"`fraud_or_security` on a non-fraud reason: {fraud_flag_other_reason}. "
        f"`requests_human` on a real topic (the \"human as flag\" convention): {human_flag_other_reason}.")
    add("")

    # ---------------------------------------------------------------- 4. confidence
    add("## 4. Confidence")
    add("")
    bands = [("≥ 0.90", lambda c: c >= 0.90), ("0.80–0.89", lambda c: 0.80 <= c < 0.90), ("0.70–0.79", lambda c: 0.70 <= c < 0.80),
             (f"{THRESHOLD:.2f}–0.69", lambda c: THRESHOLD <= c < 0.70), (f"< {THRESHOLD:.2f} (routed to a person)", lambda c: c < THRESHOLD)]
    add("| Band | n | share |")
    add("|---|---:|---:|")
    model_records = [r for r in classified if source_of(r) in ("live", "cache")]
    for label, test in bands:
        k = sum(1 for r in model_records if test(r["classification"]["confidence"]))
        add(f"| {label} | {k} | {pct(k, len(model_records))} |")
    add("")
    low = sorted((r for r in model_records if r["classification"]["confidence"] < 0.70), key=lambda r: r["classification"]["confidence"])
    add(f"Model-classified messages below 0.70 ({len(low)}), for human review first:")
    add("")
    add("| id | conf. | primary (secondary) | text |")
    add("|---|---:|---|---|")
    for r in low:
        c = r["classification"]
        sec = f" ({', '.join(c['secondary_reasons'])})" if c["secondary_reasons"] else ""
        add(f"| {r['id']} | {c['confidence']:.2f} | `{c['primary_reason']}`{sec} | {short(r['text'])} |")
    add("")

    # ---------------------------------------------------------------- 5. secondary reasons
    add("## 5. Secondary reasons (multi-intent)")
    add("")
    pairs = Counter()
    with_sec = 0
    for r in classified:
        c = r["classification"]
        if c["secondary_reasons"]:
            with_sec += 1
            for s in c["secondary_reasons"]:
                pairs[(c["primary_reason"], s)] += 1
    add(f"Messages with at least one secondary reason: {with_sec} ({pct(with_sec, len(classified))}).")
    add("")
    add("| primary → secondary | n |")
    add("|---|---:|")
    for (a, b), k in pairs.most_common(12):
        add(f"| `{a}` → `{b}` | {k} |")
    add("")

    # ---------------------------------------------------------------- 6. entities
    add("## 6. Entities (verbatim-verified)")
    add("")
    fields = ["credit_number", "document_number", "amount", "payment_date", "transaction_reference", "payment_method_or_bank", "named_agent"]
    add("| Field | messages with a value |")
    add("|---|---:|")
    for f in fields:
        k = sum(1 for r in classified if r["classification"]["entities"].get(f))
        add(f"| `{f}` | {k} |")
    masked = sum(1 for r in classified if r["classification"]["entities"].get("masked_values"))
    add(f"| `masked_values` (kept masked) | {masked} |")
    add("")

    # ---------------------------------------------------------------- 7. codes
    add("## 7. Rules and post-processing codes")
    add("")
    codes = Counter(code for r in records for code in r["rules_applied"])
    add("| Code | n |")
    add("|---|---:|")
    for code, k in sorted(codes.items(), key=lambda kv: (-kv[1], kv[0])):
        add(f"| `{code}` | {k} |")
    add("")

    # ---------------------------------------------------------------- 8. taxonomy examples
    add("## 8. Agreement with the taxonomy example ids")
    add("")
    expected = {mid: r["id"] for r in TAXONOMY["reasons"] for mid in r.get("examples", [])}
    by_id = {r["id"]: r for r in records}
    compared = [(mid, exp) for mid, exp in expected.items() if mid in by_id and by_id[mid]["classification"]]
    agree = [(mid, exp) for mid, exp in compared if by_id[mid]["classification"]["primary_reason"] == exp]
    disagree = [(mid, exp) for mid, exp in compared if by_id[mid]["classification"]["primary_reason"] != exp]
    add(f"The example ids in `taxonomy.yaml` were assigned by reading the messages while designing the "
        f"taxonomy; they are pre-labels, not a gold set. Compared: {len(compared)}; agree: {len(agree)} "
        f"({pct(len(agree), len(compared))}); disagree: {len(disagree)}.")
    add("")
    add("| id | taxonomy example of | model said | conf. | text |")
    add("|---|---|---|---:|---|")
    for mid, exp in disagree:
        c = by_id[mid]["classification"]
        sec = f" (+{', '.join(c['secondary_reasons'])})" if c["secondary_reasons"] else ""
        add(f"| {mid} | `{exp}` | `{c['primary_reason']}`{sec} | {c['confidence']:.2f} | {short(by_id[mid]['text'])} |")
    add("")

    # ---------------------------------------------------------------- 9. sentiment / language
    add("## 9. Sentiment and language")
    add("")
    sent = Counter(r["classification"]["sentiment"] for r in classified)
    lang = Counter(r["classification"]["language"] for r in classified)
    add(f"Sentiment: {', '.join(f'{k} {v}' for k, v in sent.most_common())}. Language: {', '.join(f'{k} {v}' for k, v in lang.most_common())}.")
    add("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{n} records summarised. Wrote {OUT.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_IN)
